echo 1950000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 1950000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1950000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo 1950000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo 1950000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo 1950000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo 1950000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
echo 1950000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
echo 2600000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq
echo 2600000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq
echo 2600000 > /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq
echo 2600000 > /sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq
echo 2600000 > /sys/devices/system/cpu/cpu6/cpufreq/scaling_max_freq
echo 2600000 > /sys/devices/system/cpu/cpu6/cpufreq/scaling_min_freq
echo 3105000 > /sys/devices/system/cpu/cpu7/cpufreq/scaling_max_freq
echo 3105000 > /sys/devices/system/cpu/cpu7/cpufreq/scaling_min_freq

echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
echo "performance" > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
